apps/gap/urls.py
from django.urls import path
from apps.gap.views import *

app_name = 'gap'
urlpatterns = [
    path('', RoomListView.as_view(), name='rooms'),
    path('room/<pk>', RoomDetailView.as_view(), name='room'),
    path('opinion-like/<pk>', LikeOpinionView.as_view(), name='opinion-like'),
    path('comment-like/<pk>', LikeCommentView.as_view(), name='comment-like'),
    path('comments/<pk>', OpinionDetailView.as_view(), name='comments')
]

apps/users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogoutView

app_name = 'users'
urlpatterns = [
    path('register', RegisterView.as_view(), name='register'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    # path('profile/<int:id>', ProfileView.as_view(), name='profile'),
]

config/urls.py
from django.conf.urls.static import static
from . import settings

from django.contrib import admin
from django.urls import path, include

from config.views import landing_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing_page, name='landing_page'),
    path('gap/', include('apps.gap.urls')),
    path('users/', include('apps.users.urls'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>{% block title %} Hello, world! {% endblock %}</title>
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg bg-body-tertiary mt-1">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'landing_page' %}">Gap</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'gap:rooms' %}">Rooms</a>
                    </li>
                    <li>
                        <form action="#" method="get" class="d-flex ms-4">
                            {% csrf_token %}
                            <input type="text" class="form-control" name="q" value="{{ param }}"
                                   placeholder="Search">
                            <button type="submit" class="btn btn-secondary">Search</button>
                        </form>
                    </li>
                </ul>
            </div>
            <div class="me-5 mt-2">
                <ul type="none" class="me-5">

                    {% if request.user.is_authenticated %}
                        <a href="#">
                            <button class="btn btn-secondary">{{ request.user.username }}</button>
                        </a>
                        <a href="{% url 'users:logout' %}">
                            <button class="btn btn-secondary">logout</button>
                        </a>
                    {% else %}
                        <a href="{% url 'users:login' %}">
                            <button class="btn btn-primary"> Login</button>
                        </a>
                    {% endif %}

                </ul>

            </div>
        </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
            <div class="mt-2 alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
    {% endif %}

    {% block content %}

    {% endblock %}

</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://kit.fontawesome.com/24ceb66e28.js" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
 
{% block title %}{% endblock %}

{% block content %}

<ul id="leftchapters">
          <li class="selected">Все категории</li>

          {% for cat in categories %}
                   <li><a href="#">{{cat.name}}</a></li>
          {% endfor %}
          
          <li class="share">
          <p >Наш канал</p>
          <a class="share-yt" href="..." target="_blank" rel="nofollow"></a>
          </li>
</ul>
<h3>Gap</h3>
    <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui eos beatae assumenda ea nulla error. Quia laboriosam quasi delectus. Eius accusantium obcaecati, tempore laborum sunt eligendi! Debitis saepe aliquam voluptatem quae explicabo quis necessitatibus molestias vero, nesciunt dolorum consectetur facilis quidem dolorem quas maxime nemo. Excepturi assumenda amet nostrum officia cum sit, tenetur porro in, neque aut nemo quos minus quisquam explicabo deserunt repellat! Magni nam, quae 
        officia, neque soluta animi sequi repudiandae molestiae temporibus quas mollitia minima voluptate minus, a iure. Ratione rem illum modi omnis! Vitae in quod tempora nostrum modi similique sint odio totam impedit illum aut, officiis earum ipsum, dolore delectus commodi laboriosam sit minima blanditiis eaque neque. Autem aspernatur, recusandae temporibus amet assumenda ea nam alias distinctio obcaecati eos eius, enim eveniet earum voluptatum doloremque error debitis. Vero, saepe. Cum placeat tempora 
        inventore atque vel reiciendis ipsam aspernatur! Nulla unde aspernatur odio quidem vel voluptates voluptatibus similique veniam vero dolorem, possimus eos quia dicta, debitis sequi, facilis molestias minus est nihil quas commodi officia sed. Sint laudantium optio sunt odit molestias eaque aspernatur temporibus pariatur dolorum velit exercitationem mollitia id, dolorem, corporis officia. 
        Cupiditate dicta culpa fuga nesciunt delectus repellendus odio, voluptate aperiam iusto alias expedita ipsam aspernatur distinctio. Aliquam sint, optio quas fuga, earum ut doloribus perspiciatis dolor dolores aliquid et id asperiores eum nemo consectetur. Consectetur voluptas, aut optio, alias distinctio laudantium voluptate praesentium quisquam possimus harum, omnis obcaecati 
        repellat velit saepe exercitationem. Libero optio fugit architecto tenetur perferendis, sunt temporibus velit unde molestiae ad quas consequuntur neque tempora nobis non quos suscipit laboriosam dolor numquam laborum quae? Vitae corporis, consectetur nobis eveniet libero hic, ab recusandae aliquam placeat quam debitis provident, aperiam consequatur assumenda? Rem pariatur consequuntur hic. At minus qui ratione architecto animi fuga voluptate mollitia, quaerat, cumque inventore quidem sequi.
    </p>
{% endblock %}