apps/gap/urls.py
from django.urls import path
from apps.gap.views import *

app_name = 'gap'
urlpatterns = [
    path('', RoomListView.as_view(), name='rooms'),
    path('room/<pk>', RoomDetailView.as_view(), name='room'),
    path('opinion-like/<pk>', LikeOpinionView.as_view(), name='opinion-like'),
    path('comment-like/<pk>', LikeCommentView.as_view(), name='comment-like'),
    path('comments/<pk>', OpinionDetailView.as_view(), name='comments')
]

config/urls.py
from django.conf.urls.static import static
from . import settings

from django.contrib import admin
from django.urls import path, include

from config.views import landing_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing_page, name='landing_page'),
    path('gap/', include('apps.gap.urls')),
    path('users/', include('apps.users.urls'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/gap/models.py
from apps.users.models import User
from django.db import models
from django.db.models import Model, CharField, TextField, ForeignKey, CASCADE

class AbstractModel(Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True
#p

class Room(AbstractModel):
    name = CharField(max_length=42)

    def __str__(self):
        return self.name


class Opinion(AbstractModel):
    room = ForeignKey(Room, CASCADE, 'opinions')
    title = CharField(max_length=256)
    body = TextField()
    author = ForeignKey(User, CASCADE, 'opinions')

    @property
    def like_count(self):
        return self.author.opinions.count()

    def __str__(self):
        return self.title


class OpinionLike(AbstractModel):
    user = ForeignKey(User, CASCADE, 'likes')
    opinion = ForeignKey(Opinion, CASCADE, 'opinions')

    def __str__(self):
        return f"{self.opinion}-{self.user}"



class Comment(AbstractModel):
    body = TextField()
    opinion = ForeignKey(Opinion, CASCADE, 'comments')
    author = ForeignKey(User, CASCADE, 'comments')

    @property
    def like_count(self):
        return self.opinion.likes.count()

    def __str__(self):
        return self.body
    
class CommentLike(AbstractModel):
    user = ForeignKey(User, CASCADE, 'users')
    comment = ForeignKey(Comment, CASCADE, 'comments')

    def __str__(self):
        return f"{self.comment}-{self.user}"

apps/gap/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from apps.gap.models import Room, Opinion, CommentLike,OpinionLike
from .services import *

class RoomListView(View):
   
    def get(self, request):
        context = {}
        context['rooms'] = model_objects_all(Room)
        return render(request, "gap/rooms.html",context=context)

class RoomDetailView(View):

    def get(self, request, pk):
        context = {}
        room = Room.objects.get(pk=pk)

        opinions = sorted(Opinion.objects.filter(room=room), key=lambda o: o.like_count, reverse=True)
        context['room'] = room
        context['opinions'] = opinions
        return render(request, "gap/opinions.html", context=context)
    

class LikeOpinionView(View):

    def get(self, request, pk):
        opinion = model_objects_get_pk(Opinion, pk)
        like, created = OpinionLike.objects.get_or_create(likes=request.user, opinion=opinion)
        if not created: like.delete()
        return redirect(reverse("gap:room", kwargs={"pk": opinion.room.pk}))

class LikeCommentView(View):
    def get(self, request, pk):
        comment = model_objects_get_pk(Comment, pk)
        like, created = CommentLike.objects.get_or_create(user=request.user, comment=comment)
        if not created:
            like.delete()
        return redirect(reverse("gap:room", kwargs={"pk":comment.pk}))
        
class OpinionDetailView(View):
    
    def get(self, request, pk):
        context = {}
        opinion = model_objects_get_pk(Opinion, pk)
        comments = opinion.comments.all().order_by("-created_at")
        context['opinion'] = opinion
        context['comments'] = comments
        return render(request, "gap/comments.html", context=context)
    

templates/gap/comment-cart.html
<div class="card">
    <div class="card-body">
        <h5 class="card-title">{{ opinion.title }}.</h5>
        <h6 class="card-subtitle mb-2 text-muted">{{ opinion.author }}</h6>
        <p class="card-text">{{ opinion.body }}.</p>
        <a href="{% url 'gap:comments' opinion.pk %}" class="card-link">Comments</a>
        <a href="{% url 'gap:opinion-like' opinion.pk %}" class="card-link">
   
        </a>
    </div>
</div>
     

templates/gap/comments.html
{% extends 'base.html' %}
{% block content %}
    {% include 'gap/comment-cart.html' %}

    {% for comment in comments %}
        <div class="card">
            <div class="card-header">
                {{ comment.author }}
            </div>
            <div class="card-body">
                <h5 class="card-title">Like {{ comment.comments.like_count }}</h5>
                <p class="card-text">{{ comment.body }}</p>
                <a href="{% url 'gap:comment-like' comment.pk %}" class="btn btn-primary">Like</a>
            </div>
        </div>
    {% empty %}
    <h5 class="mt-4">Now comment</h5>
    {% endfor %}

{% endblock %}

templates/gap/opinions.html
{% extends 'base.html' %}

{% block title %} Opinions {% endblock %}
{% block content %}
    {% for opinion in opinions %}
        {% include 'gap/comment-cart.html' %}
    {% endfor %}
{% endblock %}

templates/gap/rooms.html
{% extends 'base.html' %}
{% block title %} Rooms {% endblock %}

{% block content %}
    <h3>Room List</h3>
    {% for room in rooms %}
     <a href="{% url 'gap:room' room.pk %}"> {{ room }}</a> <br>
    {% endfor %}
{% endblock %}