apps/gap/urls.py
from django.urls import path
from apps.gap.views import *

app_name = 'gap'
urlpatterns = [
    path('', RoomListView.as_view(), name='rooms'),
    path('room/<pk>', RoomDetailView.as_view(), name='room'),
    path('opinion-like/<pk>', LikeOpinionView.as_view(), name='opinion-like'),
    path('comment-like/<pk>', LikeCommentView.as_view(), name='comment-like'),
    path('comments/<pk>', OpinionDetailView.as_view(), name='comments')
]

apps/users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogoutView

app_name = 'users'
urlpatterns = [
    path('register', RegisterView.as_view(), name='register'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    # path('profile/<int:id>', ProfileView.as_view(), name='profile'),
]

config/urls.py
from django.conf.urls.static import static
from . import settings

from django.contrib import admin
from django.urls import path, include

from config.views import landing_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing_page, name='landing_page'),
    path('gap/', include('apps.gap.urls')),
    path('users/', include('apps.users.urls'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass
    # avatar = models.ImageField(upload_to='users/avatar/', null=True, default='default/user/user.png')
 

apps/users/forms.py
from typing import Any
from django import forms
from .models import User
from django.core.exceptions import ValidationError

class RegisterForm(forms.ModelForm):
    def save(self, commit=True):
        user = super().save(commit=False)
        password = self.cleaned_data.get('password')
        user.set_password(password)
        user.save()
      
    class Meta:
        model = User
        fields = ['username', 
                  'first_name', 
                  'last_name', 
                  'email', 
                  'password'
                  ]
    # username = forms.CharField(widget=forms.TextInput(attrs={
    #     "type":"text", "id":"name", "placeholder":"Username..."
    # }))
    # first_name = forms.CharField(widget=forms.TextInput(attrs={
    #     "type":"text", "id":"first_name", "placeholder":"First name..."
    # }))
    # last_name = forms.CharField(widget=forms.TextInput(attrs={
    #     "type":"text", "id":"last_name", "placeholder":"Last name..."
    # }))
    # email = forms.EmailField(widget=forms.EmailInput(attrs={
    #     "type":"email", "id":"email", "placeholder":"Your email..."
    # }))
    # password = forms.CharField(widget=forms.PasswordInput(attrs={
    #     "type":"text", "id":"password", "placeholder":"password..."
    # }))
    # avatar = forms.FileField(widget=forms.FileInput(attrs={
    #     "type":"file", "id":"avatar"
    # }))
    # middle_name = forms.FileField(widget=forms.FileInput(attrs={
    #     "type":"text", "id":"middle_name"
    # }))
        
    
        

class LoginForm(forms.Form):
    username = forms.CharField(max_length=30, widget=forms.TextInput(attrs={"placeholder":"Enter sername"}))
    password = forms.CharField(max_length=30, widget=forms.PasswordInput(attrs={"placeholder":"Enter password"}))


class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 
                  'first_name', 
                  'last_name', 
                  'email', 
                  'password'
                  ]

apps/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .forms import RegisterForm, LoginForm, ProfileForm
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from apps.users.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from .services import *

class RegisterView(View):

    def get(self, request):

        form = RegisterForm()
        return render(request, 'users/register.html', {"form":form})

    def post(self, request):

        form = RegisterForm(request.POST)

        if model_registeration(request, form):

            messages.success(request, "User succesfully registered")
            return redirect('users:login')
        
        messages.warning(request, "You`r registration is are not valid !")
        return render(request, "users/register.html", {"form":form})
    

class LoginView(View):
    def get(self, request):

        form = LoginForm()
        return render(request, 'users/login.html', {"form":form})

    def post(self, request):

        form = LoginForm(request.POST)

        if form.is_valid():

            if model_login(request, form):

                return redirect('gap:rooms')
            return redirect('users:login')
        
        return render(request, "users/login.html", {"form":form})


class LogoutView(LoginRequiredMixin, View):
    
    def get(self, request):
        return render(request, 'users/logout.html')

    def post(self, request):
        logout(request)
        return redirect('gap:rooms')
    
#--------------------------------------------

# class ProfileView(LoginRequiredMixin, View):

#     def get(self, request, id):
#         user = get_object_or_404(User, id=id)
#         form = ProfileForm(instance=user)
#         return render(request,"users/profile.html", {"form":form})
    
#     def post(self, request, id):
#         user = get_object_or_404(User, id=id)
#         form = ProfileForm(request.POST, instance=user)
#         if form.is_valid():
#             form.save()
#             messages.success(request, "User succsessfully updated")
#             return redirect('gap:rooms')
#         messages.warning(request, "your acount is not valid!")
#         return render(request,"index.html.html", {"form":form})

templates/users/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Login {% endblock %}


{% block content %}
<div>
  <h3>Login</h3>
  <form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">login</button><br>
    <a href="{% url 'users:register' %}">
      Sign Up
    </a>
  </form>
</div>
{% endblock %}

templates/users/logout.html
{% extends 'base.html'%}
{% load static %}
{% block title %} Registration {% endblock %}

{% block content %}
<div class="container">
  <h3>You are logout ?</h3>
  <form action="{% url 'users:logout' %}" method="post">
    {% csrf_token %}
    <button type="submit">logout</button>
    <a href="{% url 'gap:rooms' %}">
      <button>Cancel</button>
    </a>
  </form>
</div>
{% endblock %}

templates/users/profile.html
{% extends 'base.html'%}
{% load static %}
{% block title %} Registration {% endblock %}

{% block content %}
<center>
    <h3>{{ request.user.first_name }} {{ request.user.last_name }}</h3>
    <img style="height: 30%; width: 30%;" src="{{ request.user.avatar.url }}" alt="img">
</center>
<div class="container">
    <div class="row mt-5">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">save</button>
        </form>
    </div>
</div>

{% endblock %}

templates/users/register.html
{% extends 'base.html'%}
{% load static %}
{% block title %} Registration {% endblock %}


{% block content %}
<div class="container">
  <form action="{% url 'users:register' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">register</button>
  </form>
</div>
{% endblock %}